export const Habits = [
  {
    id: 1,
    habit: {
      title: "Lire 10 pages",
      description: "Avancer dans un livre chaque jour.",
      duration: 45,
    },
    range: 40,
    more: () => {},
    action: () => {},
  },
  {
    id: 2,
    habit: {
      title: "Méditer 15 minutes",
      description: "Se recentrer grâce à la respiration.",
      duration: 60,
    },
    range: 70,
    more: () => {},
    action: () => {},
  },
  {
    id: 3,
    habit: {
      title: "Faire 30 pompes",
      description: "Renforcer son haut du corps.",
      duration: 30,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },

  {
    id: 4,
    habit: {
      title: "Marcher 8 000 pas",
      description: "Bouger davantage au quotidien.",
      duration: 90,
    },
    range: 60,
    more: () => {},
    action: () => {},
  },
  {
    id: 5,
    habit: {
      title: "Boire 2L d'eau",
      description: "S’hydrater correctement chaque jour.",
      duration: 30,
    },
    range: 50,
    more: () => {},
    action: () => {},
  },
  {
    id: 6,
    habit: {
      title: "Se lever 30 minutes plus tôt",
      description: "Créer du temps supplémentaire le matin.",
      duration: 60,
    },
    range: 40,
    more: () => {},
    action: () => {},
  },
  {
    id: 7,
    habit: {
      title: "Écrire 5 minutes",
      description: "Mettre ses pensées sur papier.",
      duration: 60,
    },
    range: 25,
    more: () => {},
    action: () => {},
  },
  {
    id: 8,
    habit: {
      title: "Apprendre une langue 10 minutes",
      description: "Progresser dans une langue étrangère.",
      duration: 180,
    },
    range: 55,
    more: () => {},
    action: () => {},
  },
  {
    id: 9,
    habit: {
      title: "Faire 10 minutes d’étirements",
      description: "Assouplir le corps et réduire les tensions.",
      duration: 45,
    },
    range: 30,
    more: () => {},
    action: () => {},
  },
  {
    id: 10,
    habit: {
      title: "Planifier sa journée",
      description: "Organiser ses priorités du jour.",
      duration: 30,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },
  {
    id: 11,
    habit: {
      title: "Lire un article éducatif",
      description: "Apprendre quelque chose de nouveau.",
      duration: 75,
    },
    range: 45,
    more: () => {},
    action: () => {},
  },
  {
    id: 12,
    habit: {
      title: "Apprendre une compétence 15 minutes",
      description: "Créer de la progression quotidienne.",
      duration: 150,
    },
    range: 65,
    more: () => {},
    action: () => {},
  },
  {
    id: 13,
    habit: {
      title: "Ranger 5 minutes",
      description: "Garder un espace propre sans effort.",
      duration: 30,
    },
    range: 10,
    more: () => {},
    action: () => {},
  },
  {
    id: 14,
    habit: {
      title: "Écouter un podcast éducatif",
      description: "Développer sa culture générale.",
      duration: 90,
    },
    range: 50,
    more: () => {},
    action: () => {},
  },
  {
    id: 15,
    habit: {
      title: "Faire 20 squats",
      description: "Renforcer les jambes.",
      duration: 30,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },
  {
    id: 16,
    habit: {
      title: "Passer 1h sans écran",
      description: "Réduire le temps digital.",
      duration: 60,
    },
    range: 40,
    more: () => {},
    action: () => {},
  },
  {
    id: 17,
    habit: {
      title: "Lire un texte spirituel",
      description: "Nourrir sa dimension intérieure.",
      duration: 45,
    },
    range: 35,
    more: () => {},
    action: () => {},
  },
  {
    id: 18,
    habit: {
      title: "Noter 3 choses positives",
      description: "Cultiver la gratitude.",
      duration: 30,
    },
    range: 15,
    more: () => {},
    action: () => {},
  },
  {
    id: 19,
    habit: {
      title: "Économiser 1€ par jour",
      description: "Créer une boule de neige d’épargne.",
      duration: 365,
    },
    range: 55,
    more: () => {},
    action: () => {},
  },
  {
    id: 20,
    habit: {
      title: "Apprendre une citation par jour",
      description: "Développer sa culture et mémoire.",
      duration: 90,
    },
    range: 35,
    more: () => {},
    action: () => {},
  },
  {
    id: 21,
    habit: {
      title: "Faire un compliment",
      description: "Créer du positif autour de soi.",
      duration: 45,
    },
    range: 15,
    more: () => {},
    action: () => {},
  },
  {
    id: 22,
    habit: {
      title: "Cuisiner un repas maison",
      description: "Manger plus sainement.",
      duration: 60,
    },
    range: 50,
    more: () => {},
    action: () => {},
  },
  {
    id: 23,
    habit: {
      title: "Faire 5 minutes de respiration",
      description: "Réduire le stress instantanément.",
      duration: 30,
    },
    range: 10,
    more: () => {},
    action: () => {},
  },
  {
    id: 44,
    habit: {
      title: "Envoyer un message à un ami",
      description: "Entretenir les relations essentielles.",
      duration: 1,
    },
    range: 5,
    more: () => {},
    action: () => {},
  },
  {
    id: 24,
    habit: {
      title: "Lire un résumé de livre",
      description: "Apprendre en version courte.",
      duration: 120,
    },
    range: 45,
    more: () => {},
    action: () => {},
  },
  {
    id: 25,
    habit: {
      title: "Étudier une notion scientifique",
      description: "Approfondir ses connaissances générales.",
      duration: 365,
    },
    range: 70,
    more: () => {},
    action: () => {},
  },
  {
    id: 26,
    habit: {
      title: "Faire 5 rituels d’étirement du dos",
      description: "Améliorer la posture.",
      duration: 45,
    },
    range: 25,
    more: () => {},
    action: () => {},
  },
  {
    id: 27,
    habit: {
      title: "Écrire une idée business",
      description: "Stimuler la créativité entrepreneuriale.",
      duration: 120,
    },
    range: 60,
    more: () => {},
    action: () => {},
  },
  {
    id: 28,
    habit: {
      title: "Écouter 10 minutes de musique relaxante",
      description: "Réduire la tension mentale.",
      duration: 45,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },
  {
    id: 29,
    habit: {
      title: "Compléter un exercice de logique",
      description: "Stimuler la réflexion.",
      duration: 180,
    },
    range: 55,
    more: () => {},
    action: () => {},
  },
  {
    id: 30,
    habit: {
      title: "Participer à une conversation enrichissante",
      description: "Développer ses échanges sociaux.",
      duration: 60,
    },
    range: 45,
    more: () => {},
    action: () => {},
  },
  {
    id: 31,
    habit: {
      title: "Écrire 1 phrase en anglais",
      description: "Améliorer le vocabulaire.",
      duration: 365,
    },
    range: 40,
    more: () => {},
    action: () => {},
  },
  {
    id: 32,
    habit: {
      title: "Apprendre un mot nouveau",
      description: "Enrichir son lexique.",
      duration: 100,
    },
    range: 25,
    more: () => {},
    action: () => {},
  },
  {
    id: 33,
    habit: {
      title: "Lire un chapitre technique",
      description: "Améliorer ses compétences pro.",
      duration: 150,
    },
    range: 55,
    more: () => {},
    action: () => {},
  },
  {
    id: 34,
    habit: {
      title: "Faire 2 séries d’abdos",
      description: "Renforcer le tronc.",
      duration: 45,
    },
    range: 30,
    more: () => {},
    action: () => {},
  },
  {
    id: 35,
    habit: {
      title: "Marcher 15 minutes dehors",
      description: "S’aérer l’esprit.",
      duration: 60,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },
  {
    id: 36,
    habit: {
      title: "Ranger son bureau",
      description: "Maintenir un espace clair.",
      duration: 30,
    },
    range: 10,
    more: () => {},
    action: () => {},
  },
  {
    id: 37,
    habit: {
      title: "Manger un fruit",
      description: "Améliorer son alimentation.",
      duration: 30,
    },
    range: 15,
    more: () => {},
    action: () => {},
  },
  {
    id: 45,
    habit: {
      title: "Faire un don symbolique",
      description: "Contribuer à une cause positive.",
      duration: 1,
    },
    range: 15,
    more: () => {},
    action: () => {},
  },
  {
    id: 38,
    habit: {
      title: "Faire une posture de yoga",
      description: "Se recentrer et étirer le corps.",
      duration: 45,
    },
    range: 25,
    more: () => {},
    action: () => {},
  },
  {
    id: 39,
    habit: {
      title: "Apprendre une règle de grammaire",
      description: "Améliorer son expression écrite.",
      duration: 180,
    },
    range: 50,
    more: () => {},
    action: () => {},
  },
  {
    id: 40,
    habit: {
      title: "Éteindre les écrans 30 minutes avant de dormir",
      description: "Améliorer la qualité du sommeil.",
      duration: 45,
    },
    range: 35,
    more: () => {},
    action: () => {},
  },
  {
    id: 41,
    habit: {
      title: "Écrire un haïku",
      description: "Stimuler la créativité poétique.",
      duration: 90,
    },
    range: 20,
    more: () => {},
    action: () => {},
  },
  {
    id: 42,
    habit: {
      title: "Sourire à 3 inconnus",
      description: "Créer une dynamique sociale positive.",
      duration: 30,
    },
    range: 10,
    more: () => {},
    action: () => {},
  },
  {
    id: 43,
    habit: {
      title: "Supprimer 1 fichier inutile",
      description: "Petit nettoyage digital.",
      duration: 9,
    },
    range: 5,
    more: () => {},
    action: () => {},
  },
] as const;
